"""empty message

Revision ID: 05de9a8ab9ff
Revises: 4e573d3ed73f
Create Date: 2021-11-08 22:39:46.621551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05de9a8ab9ff'
down_revision = '4e573d3ed73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('linea', 'origen',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('linea', 'destino',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('linea', 'destino',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('linea', 'origen',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###
