"""empty message

Revision ID: 21ae38d22e08
Revises: 65a8c8a4310b
Create Date: 2021-11-27 04:36:31.998980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ae38d22e08'
down_revision = '65a8c8a4310b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reserva', sa.Column('codigo_reserva', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'reserva', ['codigo_reserva'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reserva', type_='unique')
    op.drop_column('reserva', 'codigo_reserva')
    # ### end Alembic commands ###
