"""empty message

Revision ID: 30e0b1773a3a
Revises: 1d2e3d07be87
Create Date: 2021-11-20 22:21:45.600679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e0b1773a3a'
down_revision = '1d2e3d07be87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parada', sa.Column('id_linea', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parada', 'linea', ['id_linea'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parada', type_='foreignkey')
    op.drop_column('parada', 'id_linea')
    # ### end Alembic commands ###
