"""empty message

Revision ID: 65a8c8a4310b
Revises: 014879a2d671
Create Date: 2021-11-27 04:35:16.487617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a8c8a4310b'
down_revision = '014879a2d671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reserva', sa.Column('fecha', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reserva', 'fecha')
    # ### end Alembic commands ###
