"""empty message

Revision ID: 7bbf6ba665f4
Revises: 
Create Date: 2021-12-10 09:13:09.460949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bbf6ba665f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('linea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('nombre_linea', sa.String(length=120), nullable=False),
    sa.Column('destino', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destino'),
    sa.UniqueConstraint('nombre_linea')
    )
    op.create_table('parada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(length=120), nullable=False),
    sa.Column('latitud', sa.Float(precision=53), nullable=False),
    sa.Column('longitud', sa.Float(precision=53), nullable=False),
    sa.Column('id_linea', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_linea'], ['linea.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('latitud'),
    sa.UniqueConstraint('longitud'),
    sa.UniqueConstraint('ubicacion')
    )
    op.create_table('horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_linea', sa.Integer(), nullable=True),
    sa.Column('id_parada', sa.Integer(), nullable=True),
    sa.Column('tipo_dia', sa.String(length=80), nullable=False),
    sa.Column('hora', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['id_linea'], ['linea.id'], ),
    sa.ForeignKeyConstraint(['id_parada'], ['parada.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_linea', sa.Integer(), nullable=True),
    sa.Column('id_horario', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('asiento', sa.String(length=80), nullable=False),
    sa.Column('fecha', sa.String(length=80), nullable=False),
    sa.Column('codigo_reserva', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['id_horario'], ['horario.id'], ),
    sa.ForeignKeyConstraint(['id_linea'], ['linea.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_reserva')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva')
    op.drop_table('horario')
    op.drop_table('parada')
    op.drop_table('linea')
    op.drop_table('usuario')
    op.drop_table('empresa')
    op.drop_table('administrador')
    # ### end Alembic commands ###
